### ISSUE TITLE
Request: Icons to Add

### ISSUE THREAD

**Issue by instantdreams** [loganmarchione/homelab-svg-assets#16]
Please consider adding the following icons:

* [Adminer](https://www.adminer.org/)
* [Agent DVR](https://www.ispyconnect.com/userguide-agent-dvr.aspx)
* [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) (there is an icon available that isn't just the Prometheus logo)
* [Dashy](https://dashy.to/)
* [Homer](https://github.com/bastienwirtz/homer)
* [Kavita](https://www.kavitareader.com/) Reader
* [Loki](https://github.com/grafana/loki) by Grafana
* [mylar3](https://github.com/mylar3/mylar3/)
* [NETGEAR](https://www.netgear.com/)
* [Photoprism](https://www.photoprism.app/)
* [Static Web Server](https://github.com/static-web-server/static-web-server)
* [Teslamate](https://github.com/adriankumpf/teslamate)
* [Wyze-Bridge](https://github.com/mrlt8/docker-wyze-bridge)

If helpful, I can create requests for some of these, unless you like to track them yourself.

**Comment by loganmarchione** [comment]
* [Adminer](https://www.adminer.org/) - This was already on my [TODO](https://github.com/loganmarchione/homelab-svg-assets/blob/main/TODO.md) because there is no SVG source available to work from
* [Agent DVR](https://www.ispyconnect.com/userguide-agent-dvr.aspx) - Do you have a logo in mind? All I see is [this](https://ispycontent.azureedge.net/img/ispy2.png) PNG.
* [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) - I didn't know Alert Manager had a separate logo. Do you have a link? I can't find a SVG in their repo.
* [Dashy](https://dashy.to/) - Added to [TODO](https://github.com/loganmarchione/homelab-svg-assets/blob/main/TODO.md) because there is no SVG source available 
* [Homer](https://github.com/bastienwirtz/homer) - Done
* [Kavita](https://www.kavitareader.com/) Reader - Done
* [Loki](https://github.com/grafana/loki) by Grafana - This was already in the icon list
* [mylar3](https://github.com/mylar3/mylar3/) - Added to [TODO](https://github.com/loganmarchione/homelab-svg-assets/blob/main/TODO.md) because there is no SVG source available 
* [NETGEAR](https://www.netgear.com/) - What do you propose for this? Their wordmark is very wide, so it will be hard to read on a 48x48 logo. Do you have a link to a SVG in mind?
* [Photoprism](https://www.photoprism.app/) - Done
* [Static Web Server](https://github.com/static-web-server/static-web-server) - Done
* [Teslamate](https://github.com/adriankumpf/teslamate) - Done
* [Wyze-Bridge](https://github.com/mrlt8/docker-wyze-bridge) - Does this have a logo of its own?

**Comment by instantdreams** [comment]
* [Adminer](https://www.adminer.org/) - You are right, all I could find was an [.ico](https://raw.githubusercontent.com/vrana/adminer/master/adminer/static/favicon.ico) file
* [Agent DVR] - The [logo used for their mobile app](https://styles.redditmedia.com/t5_3i32i/styles/communityIcon_bjfpzdwolgo51.png) might work
* [Alertmanager](https://prometheus.io/docs/alerting/latest/alertmanager/) - I have been using a [shield icon](https://lenses.io/static/84d28332eeeaf98e54913604b5c7ead3/5aead/alertmanager.png) that, on further investigation, does not seem to be official. Might have to just use the Prometheus logo.
* [NETGEAR](https://www.netgear.com/) - The app store has a [shield logo](https://vectorified.com/images/netgear-icon-28.jpg) that [might fit the bill](https://noxapp.xyz/wp-content/uploads/2019/08/NETGEAR-WiFi-Analytics-App-Review-Best-Apps-for-Windows-10.png)
* [Wyze-Bridge](https://github.com/mrlt8/docker-wyze-bridge) - I guess it does not - hey, any chance you could add a [Wyze](https://play.google.com/store/apps/details?id=com.hualai) logo? :)

I very much appreciate you doing this!

**Comment by loganmarchione** [comment]
I'm open to adding any logos, but I need a link to a `.svg` file, not a `.png`. I've found it's too time consuming to trace PNGs into SVGs manually.

**Comment by instantdreams** [comment]
Oh I absolutely get that. I also feel that if an application considers branding important they'll make an SVG available.

I'll see if I can source any of these from the organisations involved.

**Comment by DragonHeart69** [comment]
Zigbee2MQTT: https://github.com/Koenkk/zigbee2mqtt/blob/master/images/logo_vector.svg

**Comment by Muromi-Rikka** [comment]
Stash https://github.com/stashapp/stash/

**Comment by loganmarchione** [comment]
> Zigbee2MQTT: https://github.com/Koenkk/zigbee2mqtt/blob/master/images/logo_vector.svg

This SVG is a mess if you open it in Inkscape and try resizing things and looking at individual components.

**Comment by loganmarchione** [comment]
> Stash https://github.com/stashapp/stash/

Done

**Comment by stanol** [comment]
Dockge https://github.com/louislam/dockge/blob/master/frontend/public/icon.svg

**Comment by loganmarchione** [comment]
> Dockge https://github.com/louislam/dockge/blob/master/frontend/public/icon.svg

Done

**Comment by robabruton** [comment]
Would you be able to add Unbound to the collection? Here's a link: https://www.nlnetlabs.nl/projects/unbound/about/
The logo on the homepage is a .svg file. Thanks!

**Comment by loganmarchione** [comment]
> Would you be able to add Unbound to the collection? Here's a link: https://www.nlnetlabs.nl/projects/unbound/about/
> 
> The logo on the homepage is a .svg file. Thanks!

Is that logo for Unbound or NLnet Labs?

**Comment by robabruton** [comment]
Sorry I didn't clarify; I was looking for the Unbound logo. Thanks!

**Comment by loganmarchione** [comment]
Closing this out. Will have users open separate issues for icons.
